package Tema04;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Gipsy Dávy
 */
public class MiDibujo extends JPanel {
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);

    // Establece el color de dibujo a verde.
        g.setColor(Color.green);
        g.fillOval(150, 70, 50, 70);

        // Cambia el color de dibujo a amarillo.
        g.setColor(Color.yellow);
        g.fillRect(350, 70, 50, 70);

        // Cambia el color de dibujo a naranja.
        g.setColor(Color.orange);

        // Define las coordenadas x del polígono (triángulo en este caso).
        int[] vx1 = {600, 650, 550};

        // Define las coordenadas y del polígono.
        int[] vy1 = {70, 120, 120};

        // Dibuja un triángulo naranja usando las coordenadas especificadas.
        g.fillPolygon(vx1, vy1, 3);
    }
    public static void main(String[] args) {
           // Crea un marco (JFrame) para mostrar el dibujo.
        JFrame frame = new JFrame();
        frame.setSize(800, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
         // Añade una instancia de MiDibujo al marco.
        frame.add(new MiDibujo());
        frame.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
